String TeacherName = "Tess Løvgreen";
int dagePrår= 365;
String by= "København";
Boolean Aktiv = true;
int Minutterprdag = 60*24;
float temperatur = 22.12
String Hej = "Hej, jeg heddder "+teachername;
Boolean Passiv = false;
float PLUS = 2.2 + 33;
char slange = 'S';
